### ISSUE TITLE
Continued error when attempting to add app to cloud foundry

### ISSUE THREAD

**Issue by jglenn1991** [ibm-developer-skills-network/qkfls-Movie-Reviews-Database#118]
[
![IBM Cloud Error](https://user-images.githubusercontent.com/108026783/185289388-30e79402-03d9-4c2a-9502-6eb08913b34e.jpg)
](url)

Keep receiving this error when attempting to complete step 5

**Comment by gislainmba** [comment]
I have the same problem and still looking for a solution.

**Comment by jglenn1991** [comment]
> I have the same problem and still looking for a solution.

So, if you do exactly what the person did in the following pull request link, it should work. 

https://github.com/ibm-developer-skills-network/qkfls-Movie-Reviews-Database/pull/119

It worked for me after doing this. If not, let me know and I can give you step-by-step instructions on how I was able to fix it.

**Comment by gislainmba** [comment]
Thanks, it worked

**Comment by captainfedoraskillup** [comment]
Closing issue.
